# -*- coding: utf-8 -*-
"""Equal-Weight_S&P_500_Index_Fund

Automatically generated by Colaboratory.
"""

!pip install -U pandas_datareader

import pandas_datareader as web
import pandas as pd
import numpy as np
import math
import requests
import datetime as dt

from google.colab import files
loaded_file = files.upload()

stocks = pd.read_csv('sp_500_stocks.csv')

stocks.head()

columns=['ticker','price','market cap','shares2buy']

df = pd.DataFrame(columns=columns)

for stock in stocks['Ticker']:
  try:
    data = web.data.get_quote_yahoo(stock)
    df = df.append(
      pd.Series([
          stock,
          np.double(data['price']),
          np.int64(data['marketCap'])[0],
          'N/A'
        ],
        index = columns
      ),
      ignore_index=True
    )
  except:
    pass

df

portfolio_size = float(input('Enter the valueof your portfolio: '))

position_size = portfolio_size / len(df.index)

for i in range(len(df.index)):
  df.loc[i,'shares2buy'] = math.floor(position_size/df.loc[i,'price'])

df
